### ISSUE TITLE
multiprocessing   TypeError: can't pickle _thread.lock objects

### ISSUE THREAD

**Issue by helloworld1973** [yyyaoyuan/CWAN#1]
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    p.start()
  File "E:\miniconda3\envs\cwan\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "E:\miniconda3\envs\cwan\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\miniconda3\envs\cwan\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\miniconda3\envs\cwan\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\miniconda3\envs\cwan\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects

**Comment by helloworld1973** [comment]
Hi friend,  
When I follow the steps, the error shows. Any ways to solve it? Thanks.
TypeError: can't pickle _thread.lock objects

**Comment by yyyaoyuan** [comment]
hi, I haven't encountered this problem. 

I have some suggestions for you:

1. you should make  sure that all the running environments are correct, they are:

python 3.6
tensorflow-gpu 1.4
CUDA 8.0
cudnn 6.0
numpy
scipy
matplotlib
scikit_learn

2. If your running environments are the same with me, but you still met this issue, maybe you can replace "p.start()" with "p.run()";

3. If the above solutions cannot solve your problem, maybe you can search this issue by Google, I believe that Google can answer you. Thanks.

**Comment by wcj456** [comment]
使用p.run()可以运行出现 但是会出现
Traceback (most recent call last):
  File "E:/桌面/异构域自适应/CWAN-main/main.py", line 101, in <module>
    p.join()
  File "D:\Anaconda\envs\cwan\lib\multiprocessing\process.py", line 123, in join
    assert self._popen is not None, 'can only join a started process'
AssertionError: can only join a started process
应该怎样修改

**Comment by yyyaoyuan** [comment]
你的所有环境是按照上面配置的吗？

**Comment by wcj456** [comment]
除了在conda里面没有安装这个 cudnn=6.0版本，安的cudnn==7.1.4，6.0版本安装不了，下载的软件 cudnn6.0版本添加到cuda 8.0文件里面了。其他环境配置都是按照上面配置的，第一次报错是TypeError: can't pickle _thread.lock objects，看了您的修改意见把p.start改成p.run，代码可以运行了， 跑了一段时间报错AssertionError: can only join a started process，有什么修改意见吗？

**Comment by yyyaoyuan** [comment]
目前是在跑这个例子吗？

source_exp = [ad.SAD, ad.SDR]
target_exp = [ad.TWS]
results_name = 'results-test'

具体跑到了什么情况？是不是已经开始执行迭代了？如果是的话，执行第几次迭代的时候开始报的错？

**Comment by wcj456** [comment]
姚先生，你好，代码跑的就是你发布的数据，上面那个例子，把p.start 换成p.run解决了线程锁问题，程序可以迭代，如下是最后的迭代次数，但是开始报错AssertionError: can only join a started process，您有什么好的建议吗？
====================iteration[450]====================
the accuracy of f(xs_1) is: 0.99858004
the accuracy of f(xs_2) is: 1.0
the accuracy of f(xl) is: 1.0
the accuracy of f(xu) is: 0.63390315
----------------------------
the delta_1 is: 0.5526251
the delta_2 is: 0.5470409
the delta_xs_1 is: 0.18872169
the delta_xs_2 is: 0.21128276
----------------------------
the loss_generator is: 218.99417
the loss_discriminator is: 1.006527
the loss_classifier is: 0.7070148
the loss_diff is: 216.78809
----------------------------
the d_pro_xs_xt is: [0.48388734 0.51611245]
the accuracy of f(xu) is: 63.39031457901001
Traceback (most recent call last):
  File "E:/桌面/异构域自适应/CWAN-main/main.py", line 101, in <module>
    p.join()
  File "D:\Anaconda\envs\cwan\lib\multiprocessing\process.py", line 123, in join
    assert self._popen is not None, 'can only join a started process'
AssertionError: can only join a started process

**Comment by yyyaoyuan** [comment]
您好，我之前都是在 linux 服务器上面跑的，用的 p.start()。我不清楚是不是因为你用的 windows 操作系统的问题。我刚才问了一下chatGPT，这是它的一个建议，你可以尝试一下。

from multiprocessing import get_context

# 使用 get_context() 方法创建上下文
ctx = get_context('spawn')  # 或者 'forkserver'

# 在此上下文中启动进程
p = ctx.Process(target=my_function, args=my_args)
p.start()
p.join()

因为我没有遇到过这个问题，所以我可能没有办法给出很好的建议，您可以尝试换一下 linux 服务器，或者询问一下谷歌/ChatGPT等，帮你调试一下问题～～～

**Comment by wcj456** [comment]
作者 你好，我是上次 报错AssertionError： can only join a started process，然后 我把 p.start（） p.join（） 屏蔽，换成p.run（）。代码可以正常运行 无报错 结果与您发布的数据也很接近
the delta_2 is: 0.5464606
the delta_xs_1 is: 0.18638018
the delta_xs_2 is: 0.22060223
----------------------------
the loss_generator is: 223.93625
the loss_discriminator is: 1.0002075
the loss_classifier is: 0.6992036
the loss_diff is: 216.22707
----------------------------
the d_pro_xs_xt is: [0.47955844 0.5204414 ]
the accuracy of f(xu) is: 59.54415798187256
[59.88604069]

进程已结束,退出代码0
您感觉这种方式可以吗？

**Comment by yyyaoyuan** [comment]
您好，我感觉只要程序可以正常退出，应该就可以了，您后续可以按照配置文件添加您自己的数据（换其它类型的数据集的话，可能需要调调参哈）进行实验。

姚远

wcj456 ***@***.***> 于2023年12月11日周一 11:03写道：
